# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "62439501cdf38ffbb892980c63df997f"
name = "Hold & Pay: Easy Reservations"
application_url = "https://hold-and-pay-dotgreen-8cca3ad5.koyeb.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "write_products,read_orders,write_orders,write_inventory,read_inventory"

[auth]
redirect_urls = [ "https://hold-and-pay-dotgreen-8cca3ad5.koyeb.app/auth/callback" ]
