# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "df7e68259cbf29848ec76a1bf153d748"
name = "Hold & Pay: Easy Reservations"
application_url = "https://hold-and-pay-dotgreen-8cca3ad5.koyeb.app"
embedded = true
distribution = "public"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,write_orders,write_inventory,read_inventory,read_customers"

[auth]
redirect_urls = [ "https://hold-and-pay-dotgreen-8cca3ad5.koyeb.app/auth/callback" ]
