api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "reserve-deposit"
type = "function"
uid = "8d4d2ab1-99d2-7fc2-3331-d069c2e7b91887c1f72e"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
